catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path('books/', views.BookListView.as_view(),name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksView.as_view(), name='all-borrowed' ),
]

urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]
# We must use pk as the name for our captured primary key value, as this is the parameter name expected by the view classes.
urlpatterns +=[
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete', views.AuthorDelete.as_view(), name='author-delete'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

######################################
# Option 2
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('catalog/', include('catalog.urls')),
#     path('', RedirectView.as_view(url='catalog/')),
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# python3 manage.py makemigrations
# python3 manage.py migrate

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

# Add URL maps to redirect the base url to our application
from django.views.generic import RedirectView
# Leave the first parameter of the path function empty to imply '/'.
urlpatterns += [
    path('',RedirectView.as_view(url='catalog/', permanent =True)),
]
# Use Static() to add url mapping to serve files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

# Add Django site authentication urls(for login, logout, password management)

urlpatterns +=[
    path('accounts/',include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Create your models here.
from django.urls import reverse

class Genre(models.Model):
    """Model representing a book genre"""
    name = models.CharField(max_length = 200, help_text = 'Enter a book genre(e.g. Science Fiction)')

    def __str__(self):
        """String for representing the model object"""
        return self.name

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name

# from django.urls import reverse

class Book(models.Model):
    """Model representing a book(but not a specific copy of a book)"""
    title = models.CharField(max_length = 200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin"""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def __str__(self):
        """String for representing the Model object"""
        return self.title

    def get_absolute_url(self):
        """Return the url to access a detail record for this book"""
        return reverse("book-detail", args=[str(self.id)])
    
import uuid
from datetime import date

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r','Reserved'),
    )

    status = models.CharField(
        max_length=1, choices=LOAN_STATUS,
        blank=True, default = 'm',
        help_text = 'Book availability'
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self):
        """String for representing the Model object"""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today()>self.due_back:
            return True
        return False


class Author(models.Model):
    """Model representing an author"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Return for representing the Model object"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """string for representing the Model object"""
        return f'{self.last_name}, {self.first_name}'
    

# py manage.py makemigration
# py manage.py migrate

catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    # Django provides numerous places where you can validate your data. The easiest way to validate a single field is to override the method clean_<fieldname>() for the field you want to check. So for example, we can validate that entered renewal_date values are between now and 4 weeks by implementing clean_renewal_date() as shown below.
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # CHeck if a date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_('Invalid Date - renewal in past'))
        
        # Check if a date is in the allowed range(+4 weeks from today)
        if data > datetime.date.today() +datetime.timedelta(weeks=4):
            raise ValidationError(_("invalid Date - Renwal more than 4 weeks ahead"))

        return data

# A basic ModelForm containing the same field as our original RenewBookForm is shown below. All you need to do to create the form is add class Meta with the associated model (BookInstance) and a list of the model fields to include in the form (you can include all fields using fields = '__all__', or you can use exclude (instead of fields) to specify the fields not to include from the model).

""" from django.forms import ModelForm
from catalog.models import BookInstance

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
         data = self.cleaned_data['due_back']

          Check if a date is not in the past.
         if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

         Check if a date is in the allowed range (+4 weeks from today).
         if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
         return data

     class Meta:
         model = BookInstance
         fields = ['due_back']
         labels = {'due_back': _('Renewal Date')}
         help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')} """

# The class RenewBookModelForm above is now functionally equivalent to our original RenewBookForm. You could import and use it wherever you currently use RenewBookForm as long as you also update the corresponding form variable name from renewal_date to due_back as in the second form declaration: RenewBookModelForm(initial={'due_back': proposed_renewal_date}.

catalog/views.py
from django.shortcuts import render
from catalog.models import Book, BookInstance, Author, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from catalog.forms import RenewBookForm
from catalog.models import Author

# Create your views here.
def index(request):

    """View function for home page of site"""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    num_genre = Genre.objects.all().count()
    num_books_count = Book.objects.filter(title__contains='The').count()

    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits + 1

    # wild_books = Book.objects.filter(title__contains='wild')

    context={
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genre': num_genre,
        'num_books_count': num_books_count,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model=Book
    paginate_by = 3

# The view passes the context (list of books) by default as object_list and book_list aliases; either will work.


    # context_object_name = 'my_book_list' #your own name for the list as a template
    # queryset = Book.objects.filter(title__icontains='The')[:5]
    # template_name = 'books/book_list.html' # Specify your own template name/location

    # def get_queryset(self):
    #     return Book.objects.filter(title__icontains='the')[:5]

    # def get_context_data(self, **kwargs):
    #     # call the base implementation first to get the context
    #     context = super(BookListView,self).get_context_data(**kwargs)
    #     # create any data and add it to the context
    #     context["some_data"] = 'This is just some data'
    #     return context

class BookDetailView(generic.DetailView):
    model = Book

# All you need to do now is create a template called /locallibrary/catalog/templates/catalog/book_detail.html, and the view will pass it the database information for the specific Book record extracted by the URL mapper. Within the template you can access the list of books with the template variable named object OR book (i.e. generically "the_model_name").

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 3

class AuthorDetailView(generic.DetailView):
    model = Author

    
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user. """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class LoanedBooksView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/all_books_borrowed.html'
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian"""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method =='POST':
        # Create a form instance and populate it with data from the request (binding)
        form = RenewBookForm(request.POST)

        # CHeck if the form is valid
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL
            return HttpResponseRedirect(reverse('all-borrowed'))
        # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_data = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_data})

    context = {
        'form': form,
        'book_instance': book_instance
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2019'}

# By default, these views will redirect on success to a page displaying the newly created/edited model item, which in our case will be the author detail view we created in a previous tutorial.

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors') 
    # reverse("author-detail", args=[str(self.id)])

"""The "create" and "update" views use the same template by default, which will be named after your model: model_name_form.html (you can change the suffix to something other than _form using the template_name_suffix field in your view, for example template_name_suffix = '_other_suffix')"""

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
# By default, these views will redirect on success to a page displaying the newly created/edited model item, which in our case will be the book detail view we created in a previous tutorial.

class BookUpdate(UpdateView):
    model = Book
    fields = "__all__"

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/all_books_borrowed.html
{%extends "base_generic.html"%}

{%block content%}
<h1>All Borrowed Books</h1>
{%if bookinstance_list%}
<ul>
    {%for borbok in bookinstance_list%}
    <li class="{%if borbok.is_overdue%}text-danger{%endif%}">
        <a href="{%url 'book-detail' borbok.book.pk%}">{{borbok.book.title}}</a> ({{borbok.due_back}}) - {{borbok.borrower}}
        {% if perms.catalog.can_mark_returned%}
        <a href="{% url 'renew-book-librarian' borbok.id%}">Renew</a>
        {% endif %}
    </li>
    
    {%endfor%}
</ul>
{%else%}
<p>There are no user that has borrowed any book</p>
{%endif%}
{%endblock%}

catalog/templates/catalog/author_confirm_delete.html
<!-- The "delete" view expects to find a template named with the format model_name_confirm_delete.html (again, you can change the suffix using template_name_suffix in your view). Create the template file locallibrary/catalog/templates/catalog/author_confirm_delete.html and copy in the text below. -->

{%extends "base_generic.html"%}

{%block content%}

<h1>Delete Author</h1>

<p>Are you sure you want to <strong>delete</strong> the author: {{author}}</p>

<form action="" method="post">
    {%csrf_token%}
    <input type="submit" value="Yes, delete">
</form>

{%endblock%}

catalog/templates/catalog/author_detail.html
{%extends 'base_generic.html'%}

{%block title%}
<title>Author's Details</title>
{%endblock%}

{%block content%}
<!-- <h1>Author: {{author.first_name}}, {{author.last_name}}</h1> -->
<h1>Author: {{author}}</h1>

<p> {%if author.date_of_birth%}{{author.date_of_birth}}{%endif%} - {%if author.date_of_death%}{{author.date_of_death}}{%endif%} </p>
<br>
    <div style="margin-left: 20px; margin-top:20px">
        <h4>Books</h4>
        {%for copy in author.book_set.all%}
        <hr>
        <p><a href="{% url 'book-detail' copy.pk%}">{{copy.title}}</a>({{copy.id}})</p>
        <p>{{copy.summary}}</p>
        {%endfor%}
    </div>
{%endblock%}

catalog/templates/catalog/author_form.html
<!--The "create" and "update" views use the same template by default, which will be named after your model: model_name_form.html (you can change the suffix to something other than _form using the template_name_suffix field in your view, for example template_name_suffix = '_other_suffix') -->

{%extends "base_generic.html"%}

{%block content%}
<form action="" method="post">  
    {%csrf_token%} 
    <!-- we declare the {% csrf_token %} to ensure that our forms are resistant to CSRF attacks. -->
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{%endblock%}

catalog/templates/catalog/author_list.html
{%extends "base_generic.html"%}

{%block title%}
<title>All Authors</title>
{%endblock%}

{%block content%}
<h1>Author List</h1>
{%if author_list%}
<ul>
    {%for author in author_list%}
    <li>
        <!-- <a href="{{author.get_absolute_url}}">{{author.first_name}}, {{author.last_name}} ({%if author.date_of_birth%}{{author.date_of_birth}}{%endif%} - {%if author.date_of_death%}{{author.date_of_death}}{%else%}Not Available{%endif%})</a> -->
        <a href="{{author.get_absolute_url}}">{{author}}({%if author.date_of_birth%}{{author.date_of_birth}}{%endif%} - {%if author.date_of_death%}{{author.date_of_death}}{%else%}Not Available{%endif%})</a>
    </li>
    {%endfor%}
</ul>
{%else%}
<p>There are no Authors with the description in the library</p>
{%endif%}
{%endblock%}

<!-- The generic view will query the database to get all records for the specified model (Book) then render a template located at /locallibrary/catalog/templates/catalog/book_list.html (which we will create below). Within the template you can access the list of books with the template variable named object_list OR book_list (i.e. generically "the_model_name_list"). -->

catalog/templates/catalog/book_confirm_delete.html
<!-- The "delete" view expects to find a template named with the format model_name_confirm_delete.html (again, you can change the suffix using template_name_suffix in your view). Create the template file locallibrary/catalog/templates/catalog/author_confirm_delete.html and copy in the text below. -->

{%extends "base_generic.html"%}

{%block content%}

<h1>Delete Book</h1>

<p>Are you sure you want to <strong>delete</strong> this book: {{book}}</p>

<form action="" method="post">
    {%csrf_token%}
    <input type="submit" value="Yes, delete">
</form>

{%endblock%}

catalog/templates/catalog/book_detail.html
{%extends 'base_generic.html'%}

{%block title%}
<title>Books Details</title>
{%endblock%}

{%block content%}
<h1>Title: {{book.title}}</h1>

<p><strong>Author: </strong><a href="{%url 'author-detail' book.author.pk%}">{{book.author}}</a></p>
<p><strong>Summary: </strong>{{book.summary}}</p>
<p><strong>ISBN: </strong>{{book.isbn}}</p>
<p><strong>Language: </strong>{{book.language}}</p>
<p><strong>Genre: </strong>{{book.genre.all|join:", "}}</p>

<div style="margin-left: 20px; margin-top:20px">
    <h4>Copies</h4>

    {%for copy in book.bookinstance_set.all%}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{copy.get_status_display}}
    </p>
    {%if copy.status != 'a'%}
    <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
    {%endif%}
    <p><strong>Imprint: </strong>{{copy.imprint}}</p>
    <p class="text-muted"><strong>ID: </strong>{{copy.id}}</p>
    {%endfor%}
</div>
{%endblock%}

catalog/templates/catalog/book_form.html
<!--The "create" and "update" views use the same template by default, which will be named after your model: model_name_form.html (you can change the suffix to something other than _form using the template_name_suffix field in your view, for example template_name_suffix = '_other_suffix') -->

{%extends "base_generic.html"%}

{%block content%}
<form action="" method="post">  
    {%csrf_token%} 
    <!-- we declare the {% csrf_token %} to ensure that our forms are resistant to CSRF attacks. -->
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{%endblock%}

catalog/templates/catalog/book_list.html
{%extends "base_generic.html"%}

{%block title%}
<title>Book List</title>
{%endblock%}

{%block content%}
<h1>Book List</h1>
{%if book_list%}
<ul>
    {%for book in book_list%}
    <li>
        <a href="{{book.get_absolute_url}}">{{book.title}}</a> ({{book.author}})
    </li>
    {%endfor%}
</ul>
{%else%}
<p>There are no books in the library.</p>
{%endif%}
{%endblock%}

<!-- The generic view will query the database to get all records for the specified model (Book) then render a template located at /locallibrary/catalog/templates/catalog/book_list.html (which we will create below). Within the template you can access the list of books with the template variable named object_list OR book_list (i.e. generically "the_model_name_list"). -->

catalog/templates/catalog/book_renew_librarian.html
{%extends "base_generic.html"%}

{% block content %}
<h1>Renew: {{book_instance.book.title}}</h1>
<p>Borrower: {{book_instance.borrower}}</p>
<p {% if book_instance.is_overdue %} class="text-danger" {% endif %}>Due date</p>

<form action="" method="post">
    <!-- The {% csrf_token %} added just inside the form tags is part of Django's cross-site forgery protection. -->
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

<!-- You can also render each field as a list item (using {{ form.as_ul }} ) or as a paragraph (using {{ form.as_p }}). -->
<!-- {{ form.renewal_date }}: The whole field.
{{ form.renewal_date.errors }}: The list of errors.
{{ form.renewal_date.id_for_label }}: The id of the label.
{{ form.renewal_date.help_text }}: The field help text. -->
    

    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html"%}

{%block content%}
<h1>Borrowed Books</h1>

{%if bookinstance_list%}
<ul>
    {% for bookinst in bookinstance_list%}
    <li class="{% if bookinst.is_overdue%}text-danger{%endif%}">
        <a href="{% url 'book-detail' bookinst.book.pk%}">{{bookinst.book.title}}</a> ({{bookinst.due_back}})
    </li>
    {%endfor%}
</ul>
{%else%}
<p>There are no books borrowed</p>
{%endif%}
{%endblock%}